name=scalapack
version=2.2.0
source=https://github.com/Reference-ScaLAPACK/scalapack/archive/refs/tags/v2.2.0.tar.gz
archive=scalapack-2.2.0.tar.gz
sha256=8862fc9673acf5f87a474aaa71cd74ae27e9bbeee475dbd7292cec5b8bcbdcf3
source_dir=scalapack-2.2.0
build_dir=scalapack-2.2.0-gcc9
prefix_rel=scalapack/2.2.0-gcc9
module=scalapack/2.2.0-gcc9
depends=gcc/9.5.0,openmpi/5.0.8-gcc9,openblas/0.3.30-gcc9
