name=mpc
version=1.0.3
source=https://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz
archive=mpc-1.0.3.tar.gz
sha256=617decc6ea09889fb08ede330917a00b16809b8db88c29c31bfbb49cbf88ecc3
source_dir=mpc-1.0.3
build_dir=mpc-1.0.3
prefix_rel=mpc/1.0.3
module=mpc/1.0.3
depends=gmp/6.1.0,mpfr/4.1.0
