name=mpfr
version=4.1.0
source=https://ftp.gnu.org/gnu/mpfr/mpfr-4.1.0.tar.bz2
archive=mpfr-4.1.0.tar.bz2
sha256=feced2d430dd5a97805fa289fed3fc8ff2b094c02d05287fd6133e7f1f0ec926
source_dir=mpfr-4.1.0
build_dir=mpfr-4.1.0
prefix_rel=mpfr/4.1.0
module=mpfr/4.1.0
depends=gmp/6.1.0
