name=openmpi
version=5.0.8
source=https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-5.0.8.tar.bz2
archive=openmpi-5.0.8.tar.bz2
sha256=53131e1a57e7270f645707f8b0b65ba56048f5b5ac3f68faabed3eb0d710e449
source_dir=openmpi-5.0.8
build_dir=openmpi-5.0.8-gcc9
prefix_rel=openmpi/5.0.8-gcc9
module=openmpi/5.0.8-gcc9
depends=gcc/9.5.0
