name=openblas
version=0.3.30
source=https://github.com/OpenMathLib/OpenBLAS/releases/download/v0.3.30/OpenBLAS-0.3.30.tar.gz
archive=OpenBLAS-0.3.30.tar.gz
sha256=27342cff518646afb4c2b976d809102e368957974c250a25ccc965e53063c95d
source_dir=OpenBLAS-0.3.30
build_dir=OpenBLAS-0.3.30-gcc9
prefix_rel=openblas/0.3.30-gcc9
module=openblas/0.3.30-gcc9
depends=gcc/9.5.0
